spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/web_proj
  security:
    jwt:
      key: 'ababssxxzyz'
      expire: 4
    filter:
      order: -100
  mail:
    host: smtp.163.com
    username: springbootgood@163.com
    password: QTDCNXAAMUFGKYCC
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /